name: "e2e"

on: [push]

jobs:
  push:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '3.6.3'
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install squire
        run: |
          R.exe -e "install.packages(c('V8', 'odin', 'deSolve', 'jsonlite', 'remotes'))"
          R.exe -e "remotes::install_github(c('mrc-ide/odin.js', 'mrc-ide/squire@v0.4.8'))"
        shell: pwsh
      - name: Install Chrome
        run: |
          $LocalTempDir = $env:TEMP
          $ChromeInstaller = "ChromeInstaller.exe"
          (new-object    System.Net.WebClient).DownloadFile('http://dl.google.com/chrome/install/375.126/chrome_installer.exe', "$LocalTempDir\$ChromeInstaller")
          & "$LocalTempDir\$ChromeInstaller" /silent /install
          $Process2Monitor =  "ChromeInstaller"
          Do {
            $ProcessesFound = Get-Process | ?{$Process2Monitor -contains $_.Name} | Select-Object -ExpandProperty Name
            If ($ProcessesFound) {
              "Still running: $($ProcessesFound -join ', ')" | Write-Host; Start-Sleep -Seconds 2
            } else {
              rm "$LocalTempDir\$ChromeInstaller" -ErrorAction SilentlyContinue -Verbose
            }
          } Until (!$ProcessesFound)
        shell: pwsh
      - name: Install Chromedriver
        run: |
          $chromeVersion = [System.Diagnostics.FileVersionInfo]::GetVersionInfo("C:\Program Files (x86)\Google\Chrome\Application\chrome.exe").FileVersion
          $chromeDriverVersionPrefix = $chromeVersion.split(".")[0..2] -join "."
          $chromeDriverVersionUrl = "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_" + $chromeDriverVersionPrefix
          $chromeDriverVersion = Invoke-RestMethod -Uri $chromeDriverVersionUrl
          $chromeDriverZipLink = "https://chromedriver.storage.googleapis.com/" + $chromeDriverVersion + "/chromedriver_win32.zip"
          Write-Output "Will download $chromeDriverZipLink"
          $chromeDriverZipFileLocation = "chromedriver_win32.zip"
          Invoke-WebRequest -Uri $chromeDriverZipLink -OutFile $chromeDriverZipFileLocation
          Expand-Archive $chromeDriverZipFileLocation -Force
          Remove-Item -Path $chromeDriverZipFileLocation -Force
        shell: pwsh
      - name: Test bundle
        run: |
          npm install
          npm run build
          npm run e2e
        shell: bash
